### ISSUE TITLE
Open ToDo's from the original GitHub repo

### ISSUE THREAD

**Issue by MasterEnderman** [Ender-Development/PedestalCrafting-Patched#1]
## Bug Fixes

- [x] https://github.com/axieum/PedestalCrafting/issues/22
- [x] https://github.com/axieum/PedestalCrafting/issues/5
- [x] https://github.com/axieum/PedestalCrafting/issues/3

## Merge open PRs

- [x] https://github.com/axieum/PedestalCrafting/pull/20
- [x] https://github.com/axieum/PedestalCrafting/pull/19
- [x] https://github.com/axieum/PedestalCrafting/pull/18
- [x] https://github.com/axieum/PedestalCrafting/pull/17
- [x] https://github.com/axieum/PedestalCrafting/pull/16
- [x] https://github.com/axieum/PedestalCrafting/pull/15
- [x] https://github.com/axieum/PedestalCrafting/pull/12
- [x] https://github.com/axieum/PedestalCrafting/pull/9
- [x] https://github.com/axieum/PedestalCrafting/pull/8

## Improvements

- [x] https://github.com/axieum/PedestalCrafting/issues/4
- [ ] https://github.com/axieum/PedestalCrafting/issues/2

**Comment by MasterEnderman** [comment]
v1.2.0: added support for ingredient transformations
